/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/about/": {
    /**
     * Получить список информации о нас
     * @description Возвращает список всей информации о нас с пагинацией
     */
    get: operations["about_list"];
    /**
     * Создать информацию о нас
     * @description Создает новую информацию о нас
     */
    post: operations["about_create"];
  };
  "/api/about/{id}/": {
    /**
     * Получить информацию о нас
     * @description Возвращает детальную информацию о нас
     */
    get: operations["about_retrieve"];
    /**
     * Обновить информацию о нас
     * @description Обновляет всю информацию о нас
     */
    put: operations["about_update"];
    /**
     * Удалить информацию о нас
     * @description Удаляет информацию о нас из системы
     */
    delete: operations["about_destroy"];
    /**
     * Частично обновить информацию о нас
     * @description Обновляет отдельные поля информации о нас
     */
    patch: operations["about_partial_update"];
  };
  "/api/digital-gov/": {
    /**
     * Получить список цифровых сервисов правительства
     * @description Возвращает список всех цифровых сервисов с пагинацией
     */
    get: operations["digital_gov_list"];
    /**
     * Создать цифровой сервис
     * @description Создает новый цифровой сервис
     */
    post: operations["digital_gov_create"];
  };
  "/api/digital-gov/{id}/": {
    /**
     * Получить цифровой сервис
     * @description Возвращает детальную информацию о цифровом сервисе
     */
    get: operations["digital_gov_retrieve"];
    /**
     * Обновить цифровой сервис
     * @description Обновляет всю информацию о цифровом сервисе
     */
    put: operations["digital_gov_update"];
    /**
     * Удалить цифровой сервис
     * @description Удаляет цифровой сервис из системы
     */
    delete: operations["digital_gov_destroy"];
    /**
     * Частично обновить цифровой сервис
     * @description Обновляет отдельные поля цифрового сервиса
     */
    patch: operations["digital_gov_partial_update"];
  };
  "/api/info-service/": {
    /**
     * Получить список информационных сервисов
     * @description Возвращает список всех информационных сервисов с пагинацией
     */
    get: operations["info_service_list"];
    /**
     * Создать информационный сервис
     * @description Создает новый информационный сервис
     */
    post: operations["info_service_create"];
  };
  "/api/info-service/{id}/": {
    /**
     * Получить информационный сервис
     * @description Возвращает детальную информацию об информационном сервисе
     */
    get: operations["info_service_retrieve"];
    /**
     * Обновить информационный сервис
     * @description Обновляет всю информацию об информационном сервисе
     */
    put: operations["info_service_update"];
    /**
     * Удалить информационный сервис
     * @description Удаляет информационный сервис из системы
     */
    delete: operations["info_service_destroy"];
    /**
     * Частично обновить информационный сервис
     * @description Обновляет отдельные поля информационного сервиса
     */
    patch: operations["info_service_partial_update"];
  };
  "/api/news/": {
    /**
     * Получить список новостей
     * @description Возвращает список всех новостей с пагинацией, поиском и фильтрацией
     */
    get: operations["news_list"];
    /**
     * Создать новость
     * @description Создает новую новость. Статус по умолчанию - 'draft'
     */
    post: operations["news_create"];
  };
  "/api/news-images/": {
    /**
     * Получить список изображений новостей
     * @description Возвращает список всех изображений новостей
     */
    get: operations["news_images_list"];
    /**
     * Создать изображение
     * @description Добавляет новое изображение к новости
     */
    post: operations["news_images_create"];
  };
  "/api/news-images/{id}/": {
    /**
     * Получить изображение
     * @description Возвращает детальную информацию об изображении
     */
    get: operations["news_images_retrieve"];
    /**
     * Обновить изображение
     * @description Обновляет информацию об изображении
     */
    put: operations["news_images_update"];
    /**
     * Удалить изображение
     * @description Удаляет изображение из системы
     */
    delete: operations["news_images_destroy"];
    /**
     * Частично обновить изображение
     * @description Обновляет отдельные поля изображения
     */
    patch: operations["news_images_partial_update"];
  };
  "/api/news/{id}/": {
    /**
     * Получить новость
     * @description Возвращает детальную информацию о новости и увеличивает счетчик просмотров
     */
    get: operations["news_retrieve"];
    /**
     * Обновить новость
     * @description Обновляет всю информацию о новости
     */
    put: operations["news_update"];
    /**
     * Удалить новость
     * @description Удаляет новость из системы
     */
    delete: operations["news_destroy"];
    /**
     * Частично обновить новость
     * @description Обновляет отдельные поля новости
     */
    patch: operations["news_partial_update"];
  };
  "/api/news/published/": {
    /**
     * Получить опубликованные новости
     * @description Возвращает только опубликованные новости
     */
    get: operations["news_published_retrieve"];
  };
  "/api/news/top/": {
    /**
     * Получить топ новостей
     * @description Возвращает новости отсортированные по количеству просмотров
     */
    get: operations["news_top_retrieve"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Сериализатор для информации о нас */
    About: {
      id: number;
      /** Biz haqimizda */
      about_us?: string;
      /** Tashkilot tuzilmasi */
      tashkilot_tizulma?: string;
      /** Rahbariyat */
      gov?: string;
      /** Markaziy apparat */
      central_apparat?: string;
      /** Tuman boshqaruvi */
      district_management?: string;
      /** Faol */
      is_active?: boolean;
      /**
       * Yaratilgan sana
       * Format: date-time
       */
      created_at: string;
      /**
       * Yangilangan sana
       * Format: date-time
       */
      updated_at: string;
    };
    /** @description Сериализатор для информации о нас */
    AboutRequest: {
      /** Biz haqimizda */
      about_us?: string;
      /** Tashkilot tuzilmasi */
      tashkilot_tizulma?: string;
      /** Rahbariyat */
      gov?: string;
      /** Markaziy apparat */
      central_apparat?: string;
      /** Tuman boshqaruvi */
      district_management?: string;
      /** Faol */
      is_active?: boolean;
    };
    /** @description Сериализатор для цифрового правительства */
    DigitalGov: {
      id: number;
      /** Biz haqimizda (Raqamli) */
      about_us_digital?: string;
      /** Meva ratsioni */
      fruit_ration?: string;
      /** Zaxira */
      zahira?: string;
      /** Vakansiyalar */
      vakancies?: string;
      /** Faol */
      is_active?: boolean;
      /**
       * Yaratilgan sana
       * Format: date-time
       */
      created_at: string;
      /**
       * Yangilangan sana
       * Format: date-time
       */
      updated_at: string;
    };
    /** @description Сериализатор для цифрового правительства */
    DigitalGovRequest: {
      /** Biz haqimizda (Raqamli) */
      about_us_digital?: string;
      /** Meva ratsioni */
      fruit_ration?: string;
      /** Zaxira */
      zahira?: string;
      /** Vakansiyalar */
      vakancies?: string;
      /** Faol */
      is_active?: boolean;
    };
    /** @description Сериализатор для информационного сервиса */
    InfoService: {
      id: number;
      /** Баянот */
      bayonat?: string;
      /** Тақвим воқеа */
      taqvim_voqea?: string;
      /** Мажлис */
      majlis?: string;
      /** Матбуот анжуман */
      matbuot_anjuman?: string;
      /** Пресс-релиз */
      press_relise?: string;
      /** Faol */
      is_active?: boolean;
      /**
       * Yaratilgan sana
       * Format: date-time
       */
      created_at: string;
      /**
       * Yangilangan sana
       * Format: date-time
       */
      updated_at: string;
    };
    /** @description Сериализатор для информационного сервиса */
    InfoServiceRequest: {
      /** Баянот */
      bayonat?: string;
      /** Тақвим воқеа */
      taqvim_voqea?: string;
      /** Мажлис */
      majlis?: string;
      /** Матбуот анжуман */
      matbuot_anjuman?: string;
      /** Пресс-релиз */
      press_relise?: string;
      /** Faol */
      is_active?: boolean;
    };
    /** @description Сериализатор для новостей */
    News: {
      id: number;
      /** Sarlavha */
      title: string;
      /** URL manzil */
      slug: string;
      thumb: string;
      /** Qisqa tavsif */
      short_description?: string;
      /** Tavsif */
      description: string;
      status?: components["schemas"]["StatusEnum"];
      status_display: string;
      /** Ko'rishlar soni */
      views_count: number;
      images: readonly components["schemas"]["NewsImage"][];
      /** Faol */
      is_active?: boolean;
      /**
       * Yaratilgan sana
       * Format: date-time
       */
      created_at: string;
      /**
       * Yangilangan sana
       * Format: date-time
       */
      updated_at: string;
      /**
       * Nashr qilingan sana
       * Format: date-time
       */
      published_at?: string | null;
    };
    /** @description Сериализатор для создания и обновления новостей */
    NewsCreateUpdate: {
      id: number;
      /** Sarlavha */
      title: string;
      /** URL manzil */
      slug: string;
      /** Format: uri */
      thumb?: string | null;
      /** Qisqa tavsif */
      short_description?: string;
      /** Tavsif */
      description: string;
      status?: components["schemas"]["StatusEnum"];
      /** Faol */
      is_active?: boolean;
      /**
       * Nashr qilingan sana
       * Format: date-time
       */
      published_at?: string | null;
    };
    /** @description Сериализатор для создания и обновления новостей */
    NewsCreateUpdateRequest: {
      /** Sarlavha */
      title: string;
      /** Format: binary */
      thumb?: string | null;
      /** Qisqa tavsif */
      short_description?: string;
      /** Tavsif */
      description: string;
      status?: components["schemas"]["StatusEnum"];
      /** Faol */
      is_active?: boolean;
      /**
       * Nashr qilingan sana
       * Format: date-time
       */
      published_at?: string | null;
    };
    /** @description Сериализатор для изображений новостей */
    NewsImage: {
      id: number;
      image: string;
      /** Sarlavha */
      caption?: string;
      /** Tartib */
      order?: number;
    };
    /** @description Сериализатор для изображений новостей */
    NewsImageRequest: {
      /** Sarlavha */
      caption?: string;
      /** Tartib */
      order?: number;
    };
    PaginatedAboutList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["About"][];
    };
    PaginatedDigitalGovList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["DigitalGov"][];
    };
    PaginatedInfoServiceList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["InfoService"][];
    };
    PaginatedNewsImageList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["NewsImage"][];
    };
    PaginatedNewsList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["News"][];
    };
    /** @description Сериализатор для информации о нас */
    PatchedAboutRequest: {
      /** Biz haqimizda */
      about_us?: string;
      /** Tashkilot tuzilmasi */
      tashkilot_tizulma?: string;
      /** Rahbariyat */
      gov?: string;
      /** Markaziy apparat */
      central_apparat?: string;
      /** Tuman boshqaruvi */
      district_management?: string;
      /** Faol */
      is_active?: boolean;
    };
    /** @description Сериализатор для цифрового правительства */
    PatchedDigitalGovRequest: {
      /** Biz haqimizda (Raqamli) */
      about_us_digital?: string;
      /** Meva ratsioni */
      fruit_ration?: string;
      /** Zaxira */
      zahira?: string;
      /** Vakansiyalar */
      vakancies?: string;
      /** Faol */
      is_active?: boolean;
    };
    /** @description Сериализатор для информационного сервиса */
    PatchedInfoServiceRequest: {
      /** Баянот */
      bayonat?: string;
      /** Тақвим воқеа */
      taqvim_voqea?: string;
      /** Мажлис */
      majlis?: string;
      /** Матбуот анжуман */
      matbuot_anjuman?: string;
      /** Пресс-релиз */
      press_relise?: string;
      /** Faol */
      is_active?: boolean;
    };
    /** @description Сериализатор для создания и обновления новостей */
    PatchedNewsCreateUpdateRequest: {
      /** Sarlavha */
      title?: string;
      /** Format: binary */
      thumb?: string | null;
      /** Qisqa tavsif */
      short_description?: string;
      /** Tavsif */
      description?: string;
      status?: components["schemas"]["StatusEnum"];
      /** Faol */
      is_active?: boolean;
      /**
       * Nashr qilingan sana
       * Format: date-time
       */
      published_at?: string | null;
    };
    /** @description Сериализатор для изображений новостей */
    PatchedNewsImageRequest: {
      /** Sarlavha */
      caption?: string;
      /** Tartib */
      order?: number;
    };
    /**
     * @description * `draft` - Qoralama
     * * `published` - Nashr etilgan
     * * `archived` - Arxivda
     * @enum {string}
     */
    StatusEnum: "draft" | "published" | "archived";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Получить список информации о нас
   * @description Возвращает список всей информации о нас с пагинацией
   */
  about_list: {
    parameters: {
      query?: {
        /** @description Which field to use when ordering the results. */
        ordering?: string;
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description A search term. */
        search?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedAboutList"];
        };
      };
    };
  };
  /**
   * Создать информацию о нас
   * @description Создает новую информацию о нас
   */
  about_create: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["AboutRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["AboutRequest"];
        "multipart/form-data": components["schemas"]["AboutRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["About"];
        };
      };
    };
  };
  /**
   * Получить информацию о нас
   * @description Возвращает детальную информацию о нас
   */
  about_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Biz haqimizda. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["About"];
        };
      };
    };
  };
  /**
   * Обновить информацию о нас
   * @description Обновляет всю информацию о нас
   */
  about_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Biz haqimizda. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["AboutRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["AboutRequest"];
        "multipart/form-data": components["schemas"]["AboutRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["About"];
        };
      };
    };
  };
  /**
   * Удалить информацию о нас
   * @description Удаляет информацию о нас из системы
   */
  about_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Biz haqimizda. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  /**
   * Частично обновить информацию о нас
   * @description Обновляет отдельные поля информации о нас
   */
  about_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Biz haqimizda. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedAboutRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedAboutRequest"];
        "multipart/form-data": components["schemas"]["PatchedAboutRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["About"];
        };
      };
    };
  };
  /**
   * Получить список цифровых сервисов правительства
   * @description Возвращает список всех цифровых сервисов с пагинацией
   */
  digital_gov_list: {
    parameters: {
      query?: {
        /** @description Which field to use when ordering the results. */
        ordering?: string;
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description A search term. */
        search?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedDigitalGovList"];
        };
      };
    };
  };
  /**
   * Создать цифровой сервис
   * @description Создает новый цифровой сервис
   */
  digital_gov_create: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["DigitalGovRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["DigitalGovRequest"];
        "multipart/form-data": components["schemas"]["DigitalGovRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["DigitalGov"];
        };
      };
    };
  };
  /**
   * Получить цифровой сервис
   * @description Возвращает детальную информацию о цифровом сервисе
   */
  digital_gov_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Raqamli hukumat. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["DigitalGov"];
        };
      };
    };
  };
  /**
   * Обновить цифровой сервис
   * @description Обновляет всю информацию о цифровом сервисе
   */
  digital_gov_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Raqamli hukumat. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["DigitalGovRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["DigitalGovRequest"];
        "multipart/form-data": components["schemas"]["DigitalGovRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["DigitalGov"];
        };
      };
    };
  };
  /**
   * Удалить цифровой сервис
   * @description Удаляет цифровой сервис из системы
   */
  digital_gov_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Raqamli hukumat. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  /**
   * Частично обновить цифровой сервис
   * @description Обновляет отдельные поля цифрового сервиса
   */
  digital_gov_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Raqamli hukumat. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedDigitalGovRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedDigitalGovRequest"];
        "multipart/form-data": components["schemas"]["PatchedDigitalGovRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["DigitalGov"];
        };
      };
    };
  };
  /**
   * Получить список информационных сервисов
   * @description Возвращает список всех информационных сервисов с пагинацией
   */
  info_service_list: {
    parameters: {
      query?: {
        /** @description Which field to use when ordering the results. */
        ordering?: string;
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description A search term. */
        search?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedInfoServiceList"];
        };
      };
    };
  };
  /**
   * Создать информационный сервис
   * @description Создает новый информационный сервис
   */
  info_service_create: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["InfoServiceRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["InfoServiceRequest"];
        "multipart/form-data": components["schemas"]["InfoServiceRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["InfoService"];
        };
      };
    };
  };
  /**
   * Получить информационный сервис
   * @description Возвращает детальную информацию об информационном сервисе
   */
  info_service_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Axborot xizmati. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["InfoService"];
        };
      };
    };
  };
  /**
   * Обновить информационный сервис
   * @description Обновляет всю информацию об информационном сервисе
   */
  info_service_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Axborot xizmati. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["InfoServiceRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["InfoServiceRequest"];
        "multipart/form-data": components["schemas"]["InfoServiceRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["InfoService"];
        };
      };
    };
  };
  /**
   * Удалить информационный сервис
   * @description Удаляет информационный сервис из системы
   */
  info_service_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Axborot xizmati. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  /**
   * Частично обновить информационный сервис
   * @description Обновляет отдельные поля информационного сервиса
   */
  info_service_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Axborot xizmati. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedInfoServiceRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedInfoServiceRequest"];
        "multipart/form-data": components["schemas"]["PatchedInfoServiceRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["InfoService"];
        };
      };
    };
  };
  /**
   * Получить список новостей
   * @description Возвращает список всех новостей с пагинацией, поиском и фильтрацией
   */
  news_list: {
    parameters: {
      query?: {
        created_after?: string;
        created_before?: string;
        /** @description Фильтр по активности (true/false) */
        is_active?: string;
        /** @description Минимальное количество просмотров */
        min_views?: string;
        /** @description Сортировка (created_at, -created_at, views_count, -views_count) */
        ordering?: string;
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Поиск по заголовку и описанию */
        search?: string;
        /** @description Фильтр по статусу (draft, published, archived) */
        status?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedNewsList"];
        };
      };
    };
  };
  /**
   * Создать новость
   * @description Создает новую новость. Статус по умолчанию - 'draft'
   */
  news_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewsCreateUpdateRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["NewsCreateUpdateRequest"];
        "multipart/form-data": components["schemas"]["NewsCreateUpdateRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["NewsCreateUpdate"];
        };
      };
    };
  };
  /**
   * Получить список изображений новостей
   * @description Возвращает список всех изображений новостей
   */
  news_images_list: {
    parameters: {
      query?: {
        news?: number;
        /** @description Which field to use when ordering the results. */
        ordering?: string;
        /** @description A page number within the paginated result set. */
        page?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedNewsImageList"];
        };
      };
    };
  };
  /**
   * Создать изображение
   * @description Добавляет новое изображение к новости
   */
  news_images_create: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["NewsImageRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["NewsImageRequest"];
        "multipart/form-data": components["schemas"]["NewsImageRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["NewsImage"];
        };
      };
    };
  };
  /**
   * Получить изображение
   * @description Возвращает детальную информацию об изображении
   */
  news_images_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Yangilik rasmi. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["NewsImage"];
        };
      };
    };
  };
  /**
   * Обновить изображение
   * @description Обновляет информацию об изображении
   */
  news_images_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Yangilik rasmi. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["NewsImageRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["NewsImageRequest"];
        "multipart/form-data": components["schemas"]["NewsImageRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["NewsImage"];
        };
      };
    };
  };
  /**
   * Удалить изображение
   * @description Удаляет изображение из системы
   */
  news_images_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Yangilik rasmi. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  /**
   * Частично обновить изображение
   * @description Обновляет отдельные поля изображения
   */
  news_images_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Yangilik rasmi. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedNewsImageRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedNewsImageRequest"];
        "multipart/form-data": components["schemas"]["PatchedNewsImageRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["NewsImage"];
        };
      };
    };
  };
  /**
   * Получить новость
   * @description Возвращает детальную информацию о новости и увеличивает счетчик просмотров
   */
  news_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Yangilik. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["News"];
        };
      };
    };
  };
  /**
   * Обновить новость
   * @description Обновляет всю информацию о новости
   */
  news_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Yangilik. */
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewsCreateUpdateRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["NewsCreateUpdateRequest"];
        "multipart/form-data": components["schemas"]["NewsCreateUpdateRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["NewsCreateUpdate"];
        };
      };
    };
  };
  /**
   * Удалить новость
   * @description Удаляет новость из системы
   */
  news_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Yangilik. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  /**
   * Частично обновить новость
   * @description Обновляет отдельные поля новости
   */
  news_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this Yangilik. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedNewsCreateUpdateRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedNewsCreateUpdateRequest"];
        "multipart/form-data": components["schemas"]["PatchedNewsCreateUpdateRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["NewsCreateUpdate"];
        };
      };
    };
  };
  /**
   * Получить опубликованные новости
   * @description Возвращает только опубликованные новости
   */
  news_published_retrieve: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["News"];
        };
      };
    };
  };
  /**
   * Получить топ новостей
   * @description Возвращает новости отсортированные по количеству просмотров
   */
  news_top_retrieve: {
    parameters: {
      query?: {
        /** @description Количество новостей (по умолчанию 10) */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["News"];
        };
      };
    };
  };
}
